Repository mmrshk/innovation_forpost, pull requests merged in 2022-09, with the labels that each got.

#79 Fix/i18n and simple_form for attachments
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/admins/attachment.scss
  app/controllers/admins/attachments_controller.rb
  app/views/admins/attachments/_form.html.erb
  app/views/admins/attachments/index.html.erb
  app/views/admins/attachments/new.html.erb
  app/views/shared/_header.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  spec/factories/attachment.rb
  spec/features/create_attachment_spec.rb
  spec/features/delete_attachment_spec.rb
  spec/features/update_attachment_spec.rb
  spec/requests/admins/attachments_spec.rb
Labels: approved

#83 Feature/add full text search for articles
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/article/article_search.scss
  app/assets/stylesheets/header.scss
  app/controllers/articles_controller.rb
  app/models/article.rb
  app/views/articles/index.html.erb
  app/views/shared/_header.html.erb
  config/locales/en.yml
  config/locales/uk.yml
Labels: requested changes

#85 Feature/add translation for errors
  app/views/errors/_errors_svg.html.erb
  app/views/errors/internal_server_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/unprocessable_entity.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  config/routes.rb
Labels: approved

#101 Add language to company
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admins/companies/companies_form.scss
  app/assets/stylesheets/admins/companies/companies_index.scss
  app/controllers/admins/companies_controller.rb
  app/controllers/companies_controller.rb
  app/models/company.rb
  app/views/admins/companies/_form.html.erb
  app/views/admins/companies/index.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  db/migrate/20220902070934_add_language_to_company.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/companies.rb
  spec/features/companies/admins_companies.rb
  spec/models/company_spec.rb
Labels: for review

#103 Feature/add attachment link to the admin menu
  app/assets/stylesheets/header.scss
  app/views/shared/_header.html.erb
  config/locales/en.yml
  config/locales/uk.yml
Labels: approved

#99 Feature/company views admin
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admins/article/_popup.scss
  app/assets/stylesheets/admins/article/article.scss
  app/assets/stylesheets/admins/companies/companies_form.scss
  app/assets/stylesheets/admins/companies/companies_index.scss
  app/assets/stylesheets/admins/companies/companies_popup.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/companies.scss
  app/controllers/admins/companies_controller.rb
  app/controllers/companies_controller.rb
  app/models/company.rb
  app/views/admins/companies/_form.html.erb
  app/views/admins/companies/edit.html.erb
  app/views/admins/companies/index.html.erb
  app/views/admins/companies/new.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  db/migrate/20220902070934_add_language_to_company.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/companies.rb
  spec/features/companies/admins_companies.rb
  spec/models/company_spec.rb
  spec/requests/admins/companies_spec.rb
  spec/spec_helper.rb
Labels: for review

#68 Feature/add sorting and filtering for users
  app/assets/stylesheets/admin.scss
  app/controllers/admins/articles_controller.rb
  app/controllers/admins/attachments_controller.rb
  app/controllers/admins/users_controller.rb
  app/javascript/packs/scripts/filter.js
  app/views/admins/articles/index.html.erb
  app/views/admins/companies/index.html.erb
  app/views/admins/users/index.html.erb
  app/views/shared/_filter.html.erb
  app/views/shared/_filter_articles.erb
  app/views/shared/_filter_users.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  spec/features/attachments/create_attachment_spec.rb
  spec/features/attachments/delete_attachment_spec.rb
  spec/features/attachments/update_attachment_spec.rb
  spec/features/users/show_users_spec.rb
Labels: for review

#93 Feature/add styles to mailer and add tests
  .gitignore
  app/controllers/admins/answers_controller.rb
  app/views/admins/questions/show.html.erb
  app/views/answer_mailer/question_answered.html.erb
  config/credentials.yml.enc
  config/credentials/test.yml.enc
  config/routes.rb
  spec/factories/questions.rb
  spec/mailers/answer_mailer_spec.rb
  spec/mailers/previews/answer_mailer_preview.rb
  spec/requests/admins/answers_spec.rb
Labels: approved

#112 fix/pass-github-actions
  Gemfile.lock
  app/controllers/admins/answers_controller.rb
  app/mailers/answer_mailer.rb
  app/mailers/application_mailer.rb
  app/views/answer_mailer/question_answered.html.erb
  config/credentials.yml.enc
  config/credentials/test.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/carriervawe.rb
  spec/mailers/answer_mailer_spec.rb
  spec/requests/admins/answers_spec.rb
Labels: fix

#102 Bugfix/Optimize queries for article search
  app/controllers/articles_controller.rb
Labels: approved

#109 Fix/filter styles
  app/assets/stylesheets/admin.scss
Labels: for review

#104 Feature/presenter test
  spec/factories/articles.rb
  spec/presenters/article_presenter_spec.rb
Labels: approved

#116 Add Company links to menu
  app/views/shared/_header.html.erb
  config/locales/en.yml
  config/locales/uk.yml
Labels: for review

#115 Feature/views for admins questions
  .rubocop.yml
  Gemfile.lock
  app/assets/stylesheets/admins/question/question.scss
  app/assets/stylesheets/application.scss
  app/controllers/admins/answers_controller.rb
  app/controllers/admins/questions_controller.rb
  app/controllers/questions_controller.rb
  app/mailers/answer_mailer.rb
  app/models/answer.rb
  app/views/admins/questions/_form.html.erb
  app/views/admins/questions/edit.html.erb
  app/views/admins/questions/index.html.erb
  app/views/admins/questions/show.html.erb
  app/views/answer_mailer/question_answered.html.erb
  app/views/answer_mailer/question_answered.text.erb
  app/views/shared/_header.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  db/migrate/20220910175816_add_language_to_answers.rb
  db/schema.rb
  spec/requests/admins/answers_spec.rb
  spec/requests/questions_spec.rb
Labels: for review

#120 Feature/sorting companies by priority
  app/assets/stylesheets/admins/companies/companies_form.scss
  app/controllers/admins/companies_controller.rb
  app/controllers/companies_controller.rb
  app/models/company.rb
  app/views/admins/companies/_form.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  db/migrate/20220911183728_add_priority_to_company.rb
  db/schema.rb
  spec/factories/companies.rb
  spec/features/companies/admins_companies.rb
  spec/features/companies/companies_spec.rb
  spec/models/company_spec.rb
Labels: for review

#107 Feature/company views client
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/admins/companies/companies_form.scss
  app/assets/stylesheets/admins/companies/companies_index.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/companies/companies_index.scss
  app/assets/stylesheets/companies/docs_index.scss
  app/assets/stylesheets/companies/news_index.scss
  app/controllers/admins/companies_controller.rb
  app/controllers/companies_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/load_more.js
  app/models/company.rb
  app/presenters/company_presenter.rb
  app/views/admins/companies/_form.html.erb
  app/views/companies/_docs.html.erb
  app/views/companies/_news.html.erb
  app/views/companies/index.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  config/routes.rb
  db/migrate/20220911183728_add_priority_to_company.rb
  db/schema.rb
  public/icons/doc-file.png
  public/icons/other-file.png
  public/icons/pdf-file.png
  public/icons/wall-clock.png
  spec/factories/attachment.rb
  spec/factories/companies.rb
  spec/features/companies/admins_companies.rb
  spec/features/companies/companies_spec.rb
  spec/models/company_spec.rb
Labels: for review

#119 Add number of unreaded questions
  app/assets/stylesheets/admins/question/question.scss
  app/controllers/application_controller.rb
  app/models/question.rb
  app/views/admins/questions/show.html.erb
  app/views/shared/_header.html.erb
Labels: requested changes

#106 Feature/update attachments
  app/assets/stylesheets/admins/attachment.scss
  app/controllers/admins/attachments_controller.rb
  app/controllers/attachments_controller.rb
  app/models/attachment.rb
  app/presenters/attachment_presenter.rb
  app/views/admins/attachments/_form.html.erb
  app/views/admins/attachments/index.html.erb
  app/views/admins/attachments/show.html.erb
  app/views/attachments/show.html.erb
  config/environments/test.rb
  config/locales/en.yml
  config/locales/uk.yml
  config/routes.rb
  db/schema.rb
  spec/features/companies/companies_spec.rb
  spec/mailers/answer_mailer_spec.rb
Labels: approved

#123 Update script load_more
  app/javascript/packs/load_more.js
Labels: for review

#121 Fix/edit styles names
  app/assets/stylesheets/admins/question/question.scss
  app/views/admins/questions/index.html.erb
  app/views/admins/questions/show.html.erb
  spec/mailers/previews/answer_mailer_preview.rb
Labels: approved

#124 Feature / Add logo
  app/assets/config/manifest.js
  app/assets/images/logo.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/header.scss
  app/javascript/src/application.css
  app/views/home/index.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_tags.html.erb
  db/schema.rb
  spec/features/companies/companies_spec.rb
Labels: for review

#97 feature/resident form
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_fonts.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/companies/companies_index.scss
  app/assets/stylesheets/companies/news_index.scss
  app/assets/stylesheets/home/home.scss
  app/assets/stylesheets/mixins/button.scss
  app/assets/stylesheets/resident_forms.scss
  app/controllers/resident_forms_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/turbo_modal_controller.js
  app/javascript/packs/application.js
  app/mailers/answer_mailer.rb
  app/mailers/resident_mailer.rb
  app/models/resident_form.rb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/resident_forms/new.html.erb
  app/views/resident_mailer/new_resident_form.html.erb
  config/initializers/simple_form.rb
  config/locales/uk.yml
  config/routes.rb
  db/migrate/20220909115221_create_resident_forms.rb
  db/schema.rb
  dump.rdb
  package.json
  yarn.lock
Labels: for review

#87 feature/Add search for tag
  Gemfile.lock
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/admins/article/_index_table.scss
  app/assets/stylesheets/admins/article/article.scss
  app/assets/stylesheets/admins/article/article_form.scss
  app/assets/stylesheets/admins/attachment.scss
  app/assets/stylesheets/admins/companies/companies_index.scss
  app/assets/stylesheets/admins/question/question.scss
  app/assets/stylesheets/article/article.scss
  app/assets/stylesheets/article/article_search.scss
  app/assets/stylesheets/header.scss
  app/assets/stylesheets/tag/tag.scss
  app/assets/stylesheets/users.scss
  app/controllers/articles_controller.rb
  app/javascript/packs/accordions.js
  app/javascript/packs/active_button.js
  app/javascript/packs/application.js
  app/views/articles/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_search.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  spec/factories/articles.rb
Labels: approved
