Repository mmrshk/innovation_forpost, pull requests merged in 2022-08, with the labels that each got.

#47 Feature/last super admin protection in db
  app/controllers/admins/users_controller.rb
  app/models/user.rb
  app/views/admins/users/_form.html.erb
  app/views/admins/users/index.html.erb
  config/locales/en.yml
  config/locales/ua.yml
  config/locales/uk.yml
  config/routes.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/requests/users_spec.rb
Labels: for review

#49 Add CKeditor
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/javascripts/app.js
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js.map
  app/assets/javascripts/new_ckeditor/classic/translations/en-au.js
  app/assets/javascripts/new_ckeditor/classic/translations/en-gb.js
  app/assets/javascripts/new_ckeditor/classic/translations/uk.js
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/article/article.scss
  app/assets/stylesheets/header.scss
  app/assets/stylesheets/new_ckeditor/.keep
  app/assets/stylesheets/new_ckeditor/ckeditor.css
  app/controllers/admins/articles_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/ckeditor_embed_snippet.js
  app/models/ck_editor_image.rb
  app/views/admins/articles/_errors.html.erb
  app/views/admins/articles/_form.html.erb
  app/views/articles/index.html.erb
  app/views/articles/show.html.erb
  app/views/layouts/application.html.erb
  app/views/new_ckeditor/shared/_classic.html.erb
  app/views/shared/_article.html.erb
  app/views/shared/_messages.html.erb
  app/views/tags/show.html.erb
  config/routes.rb
  db/migrate/20220723171556_create_ck_editor_images.rb
  db/seeds.rb
Labels: wip

#30 Feature/add article views
  .gitignore
  .overcommit.yml
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/javascripts/app.js
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js.map
  app/assets/javascripts/new_ckeditor/classic/translations/en-gb.js
  app/assets/javascripts/new_ckeditor/classic/translations/uk.js
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/admins/article/article.scss
  app/assets/stylesheets/admins/article/article_form.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/article/article.scss
  app/assets/stylesheets/header.scss
  app/assets/stylesheets/new_ckeditor/.keep
  app/assets/stylesheets/new_ckeditor/ckeditor.css
  app/assets/stylesheets/tag/tag.scss
  app/controllers/admins/articles_controller.rb
  app/controllers/articles_controller.rb
  app/helpers/articles_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/ckeditor_embed_snippet.js
  app/models/ck_editor_image.rb
  app/presenters/article_presenter.rb
  app/uploaders/ck_editor_image_uploader.rb
  app/views/admins/articles/_errors.html.erb
  app/views/admins/articles/_form.html.erb
  app/views/admins/articles/edit.html.erb
  app/views/admins/articles/index.html.erb
  app/views/admins/articles/new.html.erb
  app/views/articles/index.html.erb
  app/views/articles/show.html.erb
  app/views/layouts/application.html.erb
  app/views/new_ckeditor/shared/_classic.html.erb
  app/views/shared/_article.html.erb
  app/views/shared/_messages.html.erb
  app/views/shared/_tags.html.erb
  app/views/tags/index.html.erb
  app/views/tags/show.html.erb
  config/application.rb
  config/routes.rb
  db/migrate/20220712044814_add_role_enum_to_user.rb
  db/migrate/20220723171556_create_ck_editor_images.rb
  db/schema.rb
  db/seeds.rb
  spec/features/articles/admins_articles_spec.rb
  spec/features/articles/articles_spec.rb
  spec/rails_helper.rb
Labels: for review

#56 Feature/create admin and client controller for questions
  app/controllers/admins/questions_controller.rb
  app/controllers/questions_controller.rb
  app/models/question.rb
  app/views/admins/questions/edit.html.erb
  app/views/admins/questions/index.html.erb
  app/views/questions/index.html.erb
  app/views/questions/new.html.erb
  app/views/questions/show.html.erb
  config/routes.rb
  db/schema.rb
  spec/models/answer_spec.rb
  spec/requests/questions_spec.rb
Labels: for review

#65 Perfomance optimization. Fix N+1 queries
  Gemfile
  Gemfile.lock
  app/controllers/admins/articles_controller.rb
  app/controllers/articles_controller.rb
  app/views/tags/show.html.erb
  config/environments/development.rb
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  spec/requests/articles_spec.rb
Labels: for review, approved

#69 Feature/destroy unused tags
  app/controllers/admins/articles_controller.rb
  app/forms/articles/destroy_form.rb
  spec/forms/destroy_form_spec.rb
  spec/requests/articles_spec.rb
Labels: for review, approved

#71 Updates and improvements to image uploading
  app/controllers/admins/articles_controller.rb
  app/forms/articles/base_form.rb
  app/forms/articles/create_update_form.rb
  app/forms/articles/destroy_form.rb
  app/models/article.rb
  app/models/ck_editor_image.rb
  app/services/ck_editor_image_service.rb
  app/uploaders/ck_editor_image_uploader.rb
  app/views/admins/articles/_errors.html.erb
  app/views/admins/articles/_form.html.erb
  app/views/admins/articles/edit.html.erb
  app/views/admins/articles/new.html.erb
  config/locales/en.yml
  db/migrate/20220810075137_add_url_to_ck_editor_image.rb
  db/schema.rb
  spec/factories/articles.rb
  spec/factories/ck_editor_image.rb
  spec/factories/ck_editor_image_service.rb
  spec/files/image
  spec/forms/destroy_form_spec.rb
  spec/models/article_spec.rb
  spec/models/ck_editor_image_spec.rb
  spec/rails_helper.rb
  spec/requests/articles_spec.rb
  spec/services/ck_editor_image_service.rb
  spec/spec_helper.rb
Labels: for review

#62 Fix/truncate
  app/presenters/article_presenter.rb
  app/views/shared/_article.html.erb
Labels: for review, approved

#78 bugfix/refactoring user controller with form
  app/assets/stylesheets/admin.scss
  app/controllers/admins/users_controller.rb
  app/models/user.rb
  app/views/admins/users/_form.html.erb
  app/views/admins/users/index.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
Labels: for review

#76 feature/Fix test in model document
  spec/models/document_spec.rb
Labels: for review, approved

#75 feature/change enum to strings in User model
  app/models/user.rb
  db/migrate/20220812152503_remove_role_enum_to_user.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: for review, approved

#77 Feature/add back buttons
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/admins/attachment.scss
  app/controllers/admins/attachments_controller.rb
  app/views/admins/attachments/edit.html.erb
  app/views/admins/attachments/show.html.erb
  config/initializers/carriervawe.rb
Labels: for review, approved

#82 Feature/create answers controller and mailer
  .gitignore
  .rails_best_practices.yml
  Gemfile
  Gemfile.lock
  app/controllers/admins/answers_controller.rb
  app/controllers/admins/questions_controller.rb
  app/mailers/answer_mailer.rb
  app/mailers/application_mailer.rb
  app/views/admins/questions/show.html.erb
  app/views/answer_mailer/question_answered.html.erb
  app/views/answer_mailer/question_answered.text.erb
  config/environments/development.rb
  config/environments/production.rb
  spec/fixtures/answer_mailer/question_answered
  spec/mailers/previews/answer_mailer_preview.rb
Labels: for review, wip

#84 Fix/remove figaro and outlook and add gmail
  Gemfile
  Gemfile.lock
  app/mailers/answer_mailer.rb
  app/mailers/application_mailer.rb
  config/credentials.yml.enc
  config/environments/development.rb
  config/environments/production.rb
Labels: fix

#66 Article style refactoring
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js.map
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/admins/article/_accordion.scss
  app/assets/stylesheets/admins/article/_index_table.scss
  app/assets/stylesheets/admins/article/_popup.scss
  app/assets/stylesheets/admins/article/article.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/article/article.scss
  app/assets/stylesheets/errors.scss
  app/javascript/packs/accordions.js
  app/javascript/packs/application.js
  app/models/user.rb
  app/presenters/article_presenter.rb
  app/views/admins/articles/_form.html.erb
  app/views/admins/articles/edit.html.erb
  app/views/admins/articles/index.html.erb
  app/views/admins/articles/new.html.erb
  app/views/admins/users/index.html.erb
  app/views/articles/index.html.erb
  app/views/articles/show.html.erb
  app/views/shared/_article.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_messages.html.erb
  app/views/shared/_tags.html.erb
  app/views/tags/index.html.erb
  app/views/tags/show.html.erb
  config/initializers/assets.rb
  config/locales/en.yml
  config/locales/uk.yml
  spec/features/articles/admins_articles_spec.rb
  spec/features/articles/articles_spec.rb
Labels: for review, approved

#91 Fix/signup
  app/controllers/registrations_controller.rb
Labels: fix

#89 Fix/upload to s3
  config/credentials.yml.enc
  config/initializers/carriervawe.rb
Labels: approved

#90 Update style article client
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js
  app/assets/javascripts/new_ckeditor/classic/ckeditor.js.map
  app/assets/stylesheets/admins/article/_accordion.scss
  app/assets/stylesheets/admins/article/_index_table.scss
  app/assets/stylesheets/admins/article/article.scss
  app/assets/stylesheets/admins/article/article_form.scss
  app/assets/stylesheets/article/article.scss
  app/assets/stylesheets/tag/tag.scss
  app/views/admins/articles/_form.html.erb
  app/views/shared/_article.html.erb
  app/views/shared/_tags.html.erb
  config/initializers/assets.rb
Labels: approved

#92 Use FactoryBot for seeds
  db/seeds.rb
  spec/factories/articles.rb
  spec/factories/users.rb
Labels: approved

#95 Feature/company model
  app/models/company.rb
  db/migrate/20220825093845_create_companies.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/companies.rb
  spec/models/company_spec.rb
Labels: approved

#96 Feature/company controller
  app/assets/stylesheets/companies.scss
  app/controllers/admins/companies_controller.rb
  app/controllers/companies_controller.rb
  app/views/admins/companies/_form.html.erb
  app/views/admins/companies/edit.html.erb
  app/views/admins/companies/index.html.erb
  app/views/admins/companies/new.html.erb
  app/views/companies/index.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  config/routes.rb
  spec/requests/admins/companies_spec.rb
  spec/requests/companies_spec.rb
Labels: approved

#72 Feature/add pagination to admin page
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/admin.scss
  app/controllers/admins/articles_controller.rb
  app/controllers/admins/attachments_controller.rb
  app/controllers/admins/users_controller.rb
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/limit_records.js
  app/views/admins/articles/index.html.erb
  app/views/admins/attachments/index.html.erb
  app/views/admins/users/_pagination.html.erb
  app/views/admins/users/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_filter.html.erb
  app/views/shared/_pagination.html.erb
  config/initializers/pagy.rb
  db/seeds.rb
Labels: approved
