Repository mmrshk/innovation_forpost, pull requests merged in 2022-07, with the labels that each got.

#24 update github-actions.yml
  .github/workflows/github-actions.yml
  .rubocop.yml
Labels: for review

#17 Feature/ Clean up Gemfile, remove redundant gems
  Gemfile
  Gemfile.lock
Labels: for review

#34 install simple-form and run rails g simple_form:install
  Gemfile
  Gemfile.lock
  config/initializers/simple_form.rb
  config/locales/simple_form.en.yml
  lib/templates/erb/scaffold/_form.html.erb
Labels: for review

#39 Ignore db and config folders by PreCommit Rubocop
  .overcommit.yml
  Gemfile.lock
  config/routes.rb
  db/schema.rb
Labels: for review, fix

#16 Feature/materialize UI
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/javascript/packs/application.js
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  config/cable.yml
  config/initializers/devise.rb
  package.json
  yarn.lock
Labels: for review

#27 Feature/admin pages
  app/controllers/admins/users_controller.rb
  app/controllers/admins_controller.rb
  app/helpers/admins_helper.rb
  app/models/user.rb
  app/views/admins/_navbar.html.erb
  app/views/admins/users/_form.html.erb
  app/views/admins/users/access_denied.html.erb
  app/views/admins/users/edit.html.erb
  app/views/admins/users/index.html.erb
  app/views/admins/users/new.html.erb
  app/views/admins/users/show.html.erb
  app/views/public/_404.html.erb
  config/brakeman.ignore
  config/database.yml
  config/initializers/simple_form.rb
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20220712044814_add_role_enum_to_user.rb
  db/schema.rb
  db/seeds.rb
Labels: for review, requested changes

#32 Refactor models Article and Tag
  .rails_best_practices.yml
  Gemfile
  Gemfile.lock
  app/models/article.rb
  app/models/tag.rb
  app/models/user.rb
  db/migrate/20220629173526_create_articles.rb
  db/migrate/20220629173548_create_tags.rb
  db/migrate/20220703122917_create_article_tags.rb
  db/migrate/20220715080241_change_index_to_articles.rb
  db/migrate/20220715083703_add_index_to_tags.rb
  db/migrate/20220715083937_add_index_to_article_tags.rb
  db/schema.rb
  db/seeds.rb
  spec/models/article_spec.rb
  spec/models/article_tag_spec.rb
  spec/models/tag_spec.rb
Labels: for review

#37 Feature/add model document
  Gemfile
  Gemfile.lock
  app/models/document.rb
  db/migrate/20220711195433_create_documents.rb
  db/migrate/20220711203351_add_ancestry_to_documents.rb
  db/schema.rb
  spec/factories/documents.rb
  spec/models/document_spec.rb
  spec/rails_helper.rb
Labels: for review

#43 bugfix/add fix for heroku
  Gemfile
  Gemfile.lock
  config/locales/ua.yml
  config/locales/uk.yml
Labels: for review

#44 Add increment to Tags seeds
  db/seeds.rb
Labels: fix

#40 Feature/add pages for 404, 422, 500 errors
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/errors.scss
  app/controllers/errors_controller.rb
  app/views/errors/internal_server_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/unprocessable_entity.html.erb
  config/application.rb
  config/routes.rb
  db/schema.rb
  db/seeds.rb
  public/404.html
  public/422.html
  public/500.html
  spec/requests/errors_spec.rb
Labels: for review

#45 Bugfix / fix aplication scss for error pages
  app/assets/stylesheets/application.scss
Labels: for review

#51 Feature/simplecov
  .gitignore
  Gemfile
  Gemfile.lock
  bin/rails
  config/locales/uk.yml
  db/schema.rb
  spec/spec_helper.rb
Labels: for review

#29 Feature/add articles controller
  .overcommit.yml
  .rails_best_practices.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/header.scss
  app/controllers/admins/articles_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/tags_controller.rb
  app/forms/articles/base_form.rb
  app/forms/articles/create_update_form.rb
  app/models/article.rb
  app/models/user.rb
  app/views/admins/articles/_errors.html.erb
  app/views/admins/articles/_form.html.erb
  app/views/admins/articles/edit.html.erb
  app/views/admins/articles/index.html.erb
  app/views/admins/articles/new.html.erb
  app/views/articles/index.html.erb
  app/views/articles/show.html.erb
  config/locales/en.yml
  config/locales/uk.yml
  config/routes.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/article_tags.rb
  spec/factories/articles.rb
  spec/factories/tags.rb
  spec/factories/users.rb
  spec/forms/create_form_spec.rb
  spec/forms/update_form_spec.rb
  spec/models/article_spec.rb
  spec/rails_helper.rb
  spec/requests/articles_spec.rb
  spec/requests/sessions_spec.rb
  spec/support/controller_macros.rb
  spec/support/factory_bot.rb
Labels: for review

#48 Feature/add models question and answer
  app/models/answer.rb
  app/models/question.rb
  db/migrate/20220724120525_create_questions.rb
  db/migrate/20220724121834_create_answers.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/answers.rb
  spec/factories/questions.rb
  spec/models/answer_spec.rb
  spec/models/question_spec.rb
Labels: for review

#52 Skip lit loading for specs
  .github/workflows/github-actions.yml
  config/initializers/lit.rb
  config/routes.rb
Labels: for review

#20 Feature: Add attachments
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/admins/attachment.scss
  app/assets/stylesheets/application.scss
  app/controllers/admins/attachments_controller.rb
  app/javascript/packs/application.js
  app/models/attachment.rb
  app/views/admins/attachments/_form.html.erb
  app/views/admins/attachments/edit.html.erb
  app/views/admins/attachments/index.html.erb
  app/views/admins/attachments/new.html.erb
  app/views/admins/attachments/show.html.erb
  app/views/shared/_messages.html.erb
  config/initializers/storage_setup.rb
  config/locales/active_storage.yml
  config/locales/ua.yml
  config/locales/uk.yml
  config/routes.rb
  db/migrate/20220629123359_create_active_storage_tables.active_storage.rb
  db/migrate/20220701075212_create_attachments.rb
  db/migrate/20220723112520_add_index_on_name_to_attachment.rb
  db/schema.rb
  package.json
  spec/factories/attachment.rb
  spec/features/create_attachment_spec.rb
  spec/features/delete_attachment_spec.rb
  spec/features/update_attachment_spec.rb
  spec/files/f.jpg
  spec/files/pr.jpg
  spec/models/attachment_spec.rb
  spec/rails_helper.rb
  spec/requests/admins/attachments_spec.rb
  yarn.lock
Labels: for review
